# Site settings
baseURL = "https://buta7.github.io/hugo-frances/"
languageCode = "ja"
title = "Hugo Frances"
theme = "hugo-frances-theme"
#publishDir = "docs"

[params]
	name = "Frances Hodgkins"
	description = "Landscape and still-life painter from New Zealand"
	email = "frances@hodgkins.io"
	author = "Frances Hodgkins"

[[menu.main]]
  name = "Blog"
  title = "News"
  url = "/posts"
  weight = 1

[[menu.main]]
  name = "Contact"
  title = "Cotact Me"
  url = "/contact"
  weight = 2

[[menu.main]]
  name = "About"
  title = "About this site"
  url = "/about"
  weight = 3
