# Site settings
baseURL = "https://higebobo.github.io/hugo-frances/"
languageCode = "ja"
title = "Hugo Frances"
theme = "hugo-frances-theme"
publishDir = "docs"

[params]
	name = "Frances Hodgkins"
	description = "Landscape and still-life painter from New Zealand"
	email = "frances@hodgkins.io"
	author = "Frances Hodgkins"