# Site settings
baseURL = "https://higebobo.github.io/hugo-frances/"
languageCode = "ja"
title = "Hugo Frances"
theme = "hugo-frances-theme"
publishDir = "docs"

[params]
	name = "Frances Hodgkins"
	description = "Landscape and still-life painter from New Zealand"
	email = "frances@hodgkins.io"
	author = "Frances Hodgkins"

[[menu.main]]
  name = "Blog"
  url = "posts"
  weight = 1

[[menu.main]]
  name = "Contact Us"
  url = "contact"
  weight = 2

[[menu.main]]
  name = "About"
  url = "about/"
  weight = 3
